feat: add model-based algorithms
OmniSafeAI/omnisafe pull request #212
Opened 2023-04-11 13:51 UTC by hdadong

feat: add model-based algorithms

## Types of changes

What types of changes does your code introduce? Put an `x` in all the boxes that apply:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds core functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Documentation (update in the documentation)

## Checklist

Go over all the following points, and put an `x` in all the boxes that apply.
If you are unsure about any of these, don't hesitate to ask. We are here to help!

- [x] I have read the [CONTRIBUTION](https://omnisafe.readthedocs.io/en/latest/developer/contributing.html) guide. (**required**)
- [x] My change requires a change to the documentation.
- [x] I have updated the tests accordingly. (*required for a bug fix or a new feature*)
- [x] I have updated the documentation accordingly.
- [x] I have reformatted the code using `make format`. (**required**)
- [x] I have checked the code using `make lint`. (**required**)
- [x] I have ensured `make test` pass. (**required**)

2023-04-15 15:37 UTC, zmsn-2077 requested changes

2023-04-15 15:48 UTC, rockmagma02 commented on omnisafe/algorithms/model_based/cap_pets.py
> +        assert action.shape == torch.Size(
consider use `self._logger.store(**info)` ?

2023-04-15 15:50 UTC, rockmagma02 commented on omnisafe/algorithms/model_based/cce_pets.py
> +        assert action.shape == torch.Size(
consider use `self._logger.store(**info)`

2023-04-15 15:51 UTC, rockmagma02 commented on omnisafe/algorithms/model_based/rce_pets.py
> +        assert action.shape == torch.Size(
consider use `self._logger.store(**info)`

2023-04-15 15:51 UTC, rockmagma02 commented on omnisafe/algorithms/model_based/safeloop.py
> +        assert action.shape == torch.Size(
consider use `self._logger.stroe(**info)`

2023-04-15 15:52 UTC, rockmagma02 commented on omnisafe/algorithms/model_based/base/pets.py
> +
why pass here?
```suggestion
    def _algo_reset(
        self,
        current_step,  # pylint: disable=unused-argument
    ):
        pass

    def _update_policy(
        self,
        current_step,  # pylint: disable=unused-argument
    ):
        pass

```

2023-04-21 13:05 UTC, zmsn-2077 commented on omnisafe/algorithms/model_based/planner/arc.py
> +    def _state_action_repeat(self, state: torch.Tensor, action: torch.Tensor) -> torch.Tensor:
return list

2023-04-21 13:35 UTC, zmsn-2077 commented on omnisafe/algorithms/model_based/planner/cem.py
> +        # info['elite_idxs'] = elite_idxs
del unuseful comments

2023-05-02 15:48 UTC, zmsn-2077 approved these changes
LGTM.

2023-05-02 15:55 UTC, Gaiejj commented on benchmarks/model-based/README.md
> +path ='/home/username/omnisafe/omnisafe/examples/benchmarks/exp-x/Model-Based-Benchmarks'
May be relative path better. e.g. `./examples/benchmarks/exp-x/Model-Based-Benchmarks`

2023-05-02 15:56 UTC, rockmagma02 approved these changes

2023-05-02 16:00 UTC, Gaiejj commented on omnisafe/adapter/modelbased_adapter.py
> +        self._first_log = False
```suggestion
        self._first_log: bool = False
```
The same with others.

2023-05-02 16:14 UTC, Gaiejj approved these changes
Some problems still exist, but it doesn't matter, I will open another PR to fix my issue and I will request your review.

2023-05-02 16:14 UTC, Gaiejj commented on omnisafe/adapter/modelbased_adapter.py
> +            obs (np.ndarray): The observation.
```suggestion
            obs (torch.Tensor): The observation.
```

2023-05-02 16:14 UTC, Gaiejj commented on omnisafe/adapter/modelbased_adapter.py
> +    def render(self, *args: str, **kwargs: int) -> Any:
why the ``**kwargs`` is ``int`` type ?

2023-05-02 16:14 UTC, Gaiejj commented on omnisafe/adapter/modelbased_adapter.py
> +    def _reset_log(self, idx: int | None = None) -> None:  # pylint: disable=unused-argument
why unused-argument ``idx`` maintained ?

2023-05-02 16:22 UTC, zmsn-2077 commented
Open a fix request, then fix this code details.

2023-05-02 16:23 UTC, merged