refactor(algo_wrapper, configs): rename update cycle and refactor structure
OmniSafeAI/omnisafe pull request #213
Opened 2023-04-14 08:12 UTC by Gaiejj

## Description

Rename update cycle and refactor structure.

## Types of changes

What types of changes does your code introduce? Put an `x` in all the boxes that apply:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds core functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation (update in the documentation)

## Checklist

Go over all the following points, and put an `x` in all the boxes that apply.
If you are unsure about any of these, don't hesitate to ask. We are here to help!

- [x] I have read the [CONTRIBUTION](https://github.com/OmniSafeAI/omnisafe/blob/HEAD/CONTRIBUTING.md) guide. (**required**)
- [x] My change requires a change to the documentation.
- [x] I have updated the tests accordingly. (*required for a bug fix or a new feature*)
- [x] I have updated the documentation accordingly.
- [ ] I have reformatted the code using `make format`. (**required**)
- [x] I have checked the code using `make lint`. (**required**)
- [x] I have ensured `make test` pass. (**required**)

2023-04-15 16:54 UTC, muchvo commented on omnisafe/common/experiment_grid.py
> +        def remove_duplicate(var):
```suggestion
        def check_duplicate(var):
```

2023-04-15 16:54 UTC, muchvo commented on omnisafe/common/experiment_grid.py
> +                new_var[key] = remove_duplicate(new_var[key])
```suggestion
                new_var[key] = check_duplicate(new_var[key])
```

2023-04-15 16:54 UTC, muchvo commented on omnisafe/common/experiment_grid.py
> +        return [remove_duplicate(var) for var in flat_variants]
```suggestion
        return [check_duplicate(var) for var in flat_variants]
```

2023-04-15 16:57 UTC, muchvo commented on omnisafe/common/logger.py
> +                    table.add_row(f'{key}/Mean', str(val)[:max_key_len])
```suggestion
                    table.add_row(f'{key[:max_key_len]}/Mean', str(val)[:max_key_len])
```

2023-04-15 17:02 UTC, muchvo commented on omnisafe/common/statistics_tools.py
> +        def remove_duplicate(var):
```suggestion
        def check_duplicate(var):
```

2023-04-15 17:03 UTC, muchvo commented on omnisafe/common/statistics_tools.py
> +                new_var[key] = remove_duplicate(new_var[key])
```suggestion
                new_var[key] = check_duplicate(new_var[key])
```

2023-04-15 17:03 UTC, muchvo commented on omnisafe/common/statistics_tools.py
> +        return [remove_duplicate(var) for var in flat_variants]
```suggestion
        return [check_duplicate(var) for var in flat_variants]
```

2023-04-15 19:54 UTC, zmsn-2077 commented on omnisafe/algorithms/on_policy/second_order/cpo.py
> +                # return torch.max(torch.min(data, torch.tensor(high)), torch.tensor(low))
delete this line

2023-04-15 19:55 UTC, zmsn-2077 commented on omnisafe/algorithms/on_policy/second_order/cpo.py
> +    # pylint: disable=invalid-name,too-many-arguments,too-many-locals
disable-next

2023-04-15 20:01 UTC, zmsn-2077 requested changes
I think the version can be bumped to 0.4.0. Offline and model-based will be bumped to another version.

2023-04-17 07:39 UTC, zmsn-2077 approved these changes
LGTM.

2023-04-17 07:50 UTC, muchvo approved these changes
LGTM.

2023-04-17 08:48 UTC, merged